"""Build compact Phase 9 main-text tables from frozen reporting evidence.

Reporting-only: reads the generated Phase 9 canonical CSVs and the audited H1
source. It never fits a model, changes a split/grid, recalibrates, retunes,
reselects features, or creates a new hypothesis test. Full generated tables
remain unchanged and are retained as supplement sources.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FULL = ROOT / "paper" / "phase9_outputs" / "tables"
AUDIT = ROOT / "paper" / "phase9_audit"
OUT = Path(__file__).resolve().parent / "tables"
OUT.mkdir(parents=True, exist_ok=True)

DATASET = {
    "dry_bean": "Dry Bean",
    "covertype": "Covertype",
    "human_activity_recognition": "HAR",
}
MODEL = {
    "logistic_regression": "LR",
    "small_neural_network": "Small NN",
}
PATH = {
    "conformal_harm_one_shot": "One-shot",
    "conformal_harm_recursive": "Recursive",
}


def rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def num(value: str | float) -> float:
    return float(value)


def p_fmt(value: str | float) -> str:
    x = num(value)
    return f"{x:.8f}" if x < 1e-4 else f"{x:.4f}"


def ci(lo: str | float, hi: str | float) -> str:
    return f"CI [{num(lo):.4f}, {num(hi):.4f}]"


def shortstack(*parts: object) -> str:
    return r"\shortstack{" + r"\\".join(str(part) for part in parts) + "}"


def setting(dataset: str, model: str, path: str) -> str:
    return shortstack(dataset, f"{model} / {path}")


def write_csv(path: Path, records: list[dict[str, object]]) -> None:
    if not records:
        raise ValueError(f"No records for {path}")
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(records[0]))
        writer.writeheader()
        writer.writerows(records)


def tex_escape(value: object) -> str:
    # Preserve TeX commands generated by this script; escape only plain cells.
    text = str(value)
    if text.startswith(r"\shortstack{"):
        return text
    for old, new in (("_", r"\_"), ("%", r"\%"), ("&", r"\&"), ("#", r"\#")):
        text = text.replace(old, new)
    return text


def write_tex(
    path: Path,
    caption: str,
    label: str,
    headers: list[str],
    body: list[list[object]],
    *,
    table_star: bool = True,
    size_command: str = r"\scriptsize",
) -> None:
    env = "table*" if table_star else "table"
    lines = [
        rf"\begin{{{env}}}[t]",
        r"\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        size_command,
        r"\begin{tabular}{" + "l" * len(headers) + "}",
        r"\hline",
        " & ".join(headers) + r" \\",
        r"\hline",
    ]
    lines.extend(" & ".join(tex_escape(value) for value in record) + r" \\" for record in body)
    lines.extend([r"\hline", r"\end{tabular}", rf"\end{{{env}}}"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def compact_t1() -> None:
    src = rows(FULL / "table_t1_design_audit.csv")
    if len(src) != 3:
        raise AssertionError(f"T1 row count: {len(src)}")
    body = []
    for r in src:
        body.append([
            r["dataset"], r["paired_seeds"], r["seed_range"], r["dataset_seed_units"],
            f'{int(r["aggregate_rows"]):,}', f'{int(r["subject_rows"]):,}',
            r["split_regime"], r["final_precision"], r["scientific_code"],
        ])
    write_tex(
        OUT / "table_t1_design_audit_main.tex",
        "Frozen Phase 8 audit population. Aggregate rows are experiment-result rows; HAR subject rows are subject-condition records for clustered subject analysis, not independent subjects. Final precision = Met denotes satisfaction of the frozen precision stopping rule only and does not establish efficacy, statistical significance, numerical safety, or nominal conformal coverage. HAR splitting is subject-disjoint.",
        "tab:t1-design-audit",
        ["Dataset", "Seeds", "Seed range", "Units", "Aggregate rows", "Subject rows", "Split", "Precision", "Code"],
        body,
    )


def compact_t2() -> None:
    src = rows(FULL / "table_t2_primary_results.csv")
    refs = {(r["dataset"], r["model"]): r for r in src if r["method"] == "All features"}
    selected = [r for r in src if r["method"] in {"One-shot", "Recursive"}]
    assert len(refs) == 6 and len(selected) == 12
    records: list[dict[str, object]] = []
    body: list[list[object]] = []
    for r in selected:
        ref = refs[(r["dataset"], r["model"])]
        rec = {
            "dataset": r["dataset"], "model": r["model"], "path": r["method"],
            "all_mean_size": num(ref["mean_size"]), "selected_mean_size": num(r["mean_size"]),
            "size_reduction": num(r["size_mean_difference"]),
            "size_ci_lower": num(r["size_ci_lower"]), "size_ci_upper": num(r["size_ci_upper"]),
            "size_holm_sign_flip_p": num(r["size_holm_sign_flip_pvalue"]),
            "all_accuracy": num(ref["accuracy"]), "selected_accuracy": num(r["accuracy"]),
            "accuracy_difference": num(r["accuracy_mean_difference"]),
            "accuracy_ci_lower": num(r["accuracy_ci_lower"]), "accuracy_ci_upper": num(r["accuracy_ci_upper"]),
            "accuracy_holm_sign_flip_p": num(r["accuracy_holm_sign_flip_pvalue"]),
            "all_coverage": num(ref["coverage"]), "selected_coverage": num(r["coverage"]),
        }
        records.append(rec)
        body.append([
            setting(r["dataset"], r["model"], r["method"]),
            f'{rec["selected_mean_size"]:.4f}',
            shortstack(f'{rec["size_reduction"]:.4f}', ci(rec["size_ci_lower"], rec["size_ci_upper"]), f'Holm p={p_fmt(rec["size_holm_sign_flip_p"])}'),
            f'{rec["selected_accuracy"]:.4f}',
            shortstack(f'{rec["accuracy_difference"]:.4f}', ci(rec["accuracy_ci_lower"], rec["accuracy_ci_upper"]), f'Holm p={p_fmt(rec["accuracy_holm_sign_flip_p"])}'),
            f'{rec["selected_coverage"]:.4f}',
        ])
    write_csv(OUT / "table_t2_primary_compact.csv", records)
    write_tex(
        OUT / "table_t2_primary_compact.tex",
        r"Primary Base-APS results at $\alpha=0.10$ with tuning accuracy-loss allowance 0.01. Size reduction is all-feature minus selected mean size (positive favors removal); accuracy difference is selected minus all-feature accuracy (positive favors removal). Effect cells show estimate, paired Student-$t$ 95\% CI, and Holm-adjusted exact sign-flip $p$. Coverage is descriptive; no new coverage interval or noninferiority claim is implied.",
        "tab:t2-primary-compact",
        ["Setting", "Selected size", r"$\Delta$ size vs all", "Selected accuracy", r"$\Delta$ accuracy vs all", "Selected coverage"],
        body,
    )


def compact_h1() -> None:
    overlap = rows(AUDIT / "h1_overlap_verified.csv")
    stability = rows(FULL / "table_t3b_rank_stability.csv")
    stable = {
        (r["dataset"], r["model"], r["method"]): r
        for r in stability
        if r["stability_type"] == "progressive_removal_path" and r["top_k"] == "1"
    }
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = {}
    for r in overlap:
        key = (DATASET[r["dataset"]], MODEL[r["model"]], PATH[r["proposed"]])
        grouped.setdefault(key, []).append(r)
    assert len(grouped) == 12 and all(len(group) == 5 for group in grouped.values())
    records: list[dict[str, object]] = []
    body: list[list[object]] = []
    for (dataset, model, path), group in sorted(grouped.items()):
        n_values = {int(r["n"]) for r in group}
        removed_values = {num(r["mean_removed"]) for r in group}
        assert len(n_values) == 1 and len(removed_values) == 1
        s = stable[(dataset, model, path)]
        jaccards = [num(r["jaccard_mean"]) for r in group]
        rec = {
            "dataset": dataset, "model": model, "path": path,
            "within_seed_overlap_n": next(iter(n_values)),
            "mean_removed": next(iter(removed_values)),
            "jaccard_vs_standards_min": min(jaccards), "jaccard_vs_standards_max": max(jaccards),
            "across_seed_pair_count": int(s["seed_pairs"]),
            "top1_jaccard_across_seeds": num(s["jaccard_mean"]),
        }
        records.append(rec)
        body.append([
            setting(dataset, model, path), rec["within_seed_overlap_n"], f'{rec["mean_removed"]:.2f}',
            f'{rec["jaccard_vs_standards_min"]:.4f}--{rec["jaccard_vs_standards_max"]:.4f}',
            rec["across_seed_pair_count"], f'{rec["top1_jaccard_across_seeds"]:.4f}',
        ])
    write_csv(OUT / "table_t3_h1_compact.csv", records)
    write_tex(
        OUT / "table_t3_h1_compact.tex",
        r"Selection distinctness and identity stability. Within-seed Jaccard ranges summarize the five size-matched conventional selectors at the same seed and removed-feature count; zero-removal cases are excluded only from this overlap estimand and the conditional $n$ is shown. Across-seed top-1 Jaccard is computed over overlapping seed pairs (45 for Covertype, 190 for the 20-seed datasets), which are not independent replications.",
        "tab:t3-h1-compact",
        ["Setting", "Overlap n", "Mean removed", "Within-seed Jaccard range", "Seed pairs", "Across-seed top-1 Jaccard"],
        body,
    )


def compact_baselines() -> None:
    src = [r for r in rows(FULL / "table_t3a_matched_baselines.csv") if r["metric"] == "mean_size"]
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = {}
    for r in src:
        grouped.setdefault((r["dataset"], r["model"], r["method"]), []).append(r)
    assert len(grouped) == 12 and all(len(group) == 5 for group in grouped.values())
    records: list[dict[str, object]] = []
    body: list[list[object]] = []
    for (dataset, model, path), group in sorted(grouped.items()):
        wins = [
            r["reference_method"] for r in group
            if num(r["mean_difference"]) > 0 and num(r["holm_sign_flip_pvalue"]) < 0.05
        ]
        effects = [num(r["mean_difference"]) for r in group]
        n_values = {int(r["n_pairs"]) for r in group}
        assert len(n_values) == 1
        rec = {
            "dataset": dataset, "model": model, "path": path, "n_pairs": next(iter(n_values)),
            "target_size_min": min(int(r["target_size_min"]) for r in group),
            "target_size_max": max(int(r["target_size_max"]) for r in group),
            "significant_size_wins_of_5": len(wins),
            "significant_comparators": ",".join(wins) if wins else "None",
            "size_gain_min": min(effects), "size_gain_max": max(effects),
        }
        records.append(rec)
        body.append([
            setting(dataset, model, path), rec["n_pairs"], f'{rec["target_size_min"]}--{rec["target_size_max"]}',
            f'{len(wins)}/5', rec["significant_comparators"].replace(",", ", "),
            f'{rec["size_gain_min"]:.4f}--{rec["size_gain_max"]:.4f}',
        ])
    write_csv(OUT / "table_t3_matched_baselines_compact.csv", records)
    write_tex(
        OUT / "table_t3_matched_baselines_compact.tex",
        r"Size-matched comparator summary. Positive point effects mean smaller mean prediction sets for the proposed subset. Wins count the five prespecified selectors whose supplied Holm-adjusted exact sign-flip $p<0.05$ and whose effect favors the proposed method; this is a descriptive reduction of the five corrected contrasts, not a new test. Full intervals, effect sizes and $p$ values remain in Supplementary Table T3a.",
        "tab:t3-baseline-compact",
        ["Setting", "n", "Matched retained range", "Wins", "Comparators beaten", "Point-effect range"],
        body,
    )


def compact_t4() -> None:
    src = [r for r in rows(FULL / "table_t4_scaling_interaction.csv") if r["scaling"] == "confts"]
    assert len(src) == 12
    records: list[dict[str, object]] = []
    body: list[list[object]] = []
    for r in src:
        rec = {
            "dataset": r["dataset"], "model": r["model"], "path": r["method"], "n": int(r["n"]),
            "feature_gain_under_confts": num(r["feature_size_gain"]),
            "feature_ci_lower": num(r["feature_ci_lo"]), "feature_ci_upper": num(r["feature_ci_hi"]),
            "all_feature_confts_scaling_gain": num(r["scaling_size_gain_all"]),
            "scaling_ci_lower": num(r["scaling_ci_lo"]), "scaling_ci_upper": num(r["scaling_ci_hi"]),
            "combined_gain_vs_base_all": num(r["combined_size_gain_vs_base_all"]),
            "combined_ci_lower": num(r["comb_ci_lo"]), "combined_ci_upper": num(r["comb_ci_hi"]),
            "additive_excess": num(r["interaction"]),
            "interaction_ci_lower": num(r["int_ci_lo"]), "interaction_ci_upper": num(r["int_ci_hi"]),
            "selected_confts_mean_size": num(r["mean_size"]),
            "selected_confts_coverage": num(r["coverage"]),
        }
        records.append(rec)
        effect = lambda est, lo, hi: shortstack(f'{rec[est]:.4f}', ci(rec[lo], rec[hi]))
        body.append([
            setting(r["dataset"], r["model"], r["method"]),
            effect("feature_gain_under_confts", "feature_ci_lower", "feature_ci_upper"),
            effect("all_feature_confts_scaling_gain", "scaling_ci_lower", "scaling_ci_upper"),
            effect("combined_gain_vs_base_all", "combined_ci_lower", "combined_ci_upper"),
            effect("additive_excess", "interaction_ci_lower", "interaction_ci_upper"),
            shortstack(f'size={rec["selected_confts_mean_size"]:.4f}', f'cov={rec["selected_confts_coverage"]:.4f}'),
        ])
    write_csv(OUT / "table_t4_scaling_compact.csv", records)
    write_tex(
        OUT / "table_t4_scaling_compact.tex",
        r"Frozen APS feature-removal $\times$ ConfTS interaction at $\alpha=0.10$. Feature gain is all-ConfTS minus selected-ConfTS size; scaling gain is all-Base minus all-ConfTS; combined gain is all-Base minus selected-ConfTS. Positive values indicate smaller sets. Additive excess is $B+C-A-D$; negative values indicate sub-additivity. Cells show estimate and supplied 95\% CI. H3 means were independently reconciled, but interval values remain supplied Phase 8 evidence because their original generator is unavailable.",
        "tab:t4-scaling-compact",
        ["Setting", "Feature gain", "Scaling gain", "Combined gain", "Additive excess", "Selected ConfTS"],
        body,
    )


def compact_t5() -> None:
    src = rows(FULL / "table_t5a_har_subject_effects.csv")
    grouped: dict[tuple[str, str], dict[str, dict[str, str]]] = {}
    for r in src:
        grouped.setdefault((r["model"], r["method"]), {})[r["metric"]] = r
    assert len(grouped) == 4 and all(
        set(metrics) == {"mean_size_reduction_vs_all", "coverage_difference_vs_all"}
        for metrics in grouped.values()
    )
    records: list[dict[str, object]] = []
    body: list[list[object]] = []
    for (model, path), metrics in sorted(grouped.items()):
        size = metrics["mean_size_reduction_vs_all"]
        coverage = metrics["coverage_difference_vs_all"]
        for field in ("n_cells", "n_seeds", "n_subjects", "bootstrap_repetitions"):
            assert size[field] == coverage[field]
        rec = {
            "dataset": "HAR", "model": model, "path": path,
            "n_cells": int(size["n_cells"]), "n_seeds": int(size["n_seeds"]),
            "n_unique_subjects": int(size["n_subjects"]),
            "size_reduction": num(size["mean_difference"]),
            "size_ci_lower": num(size["ci_lower"]), "size_ci_upper": num(size["ci_upper"]),
            "coverage_difference": num(coverage["mean_difference"]),
            "coverage_ci_lower": num(coverage["ci_lower"]), "coverage_ci_upper": num(coverage["ci_upper"]),
            "bootstrap_repetitions": int(size["bootstrap_repetitions"]),
        }
        records.append(rec)
        body.append([
            shortstack(model, path), rec["n_cells"], shortstack(f'{rec["n_seeds"]} seeds', f'{rec["n_unique_subjects"]} subjects'),
            shortstack(f'{rec["size_reduction"]:.4f}', ci(rec["size_ci_lower"], rec["size_ci_upper"])),
            shortstack(f'{rec["coverage_difference"]:.4f}', ci(rec["coverage_ci_lower"], rec["coverage_ci_upper"])),
            rec["bootstrap_repetitions"],
        ])
    write_csv(OUT / "table_t5_har_subject_compact.csv", records)
    write_tex(
        OUT / "table_t5_har_subject_compact.tex",
        r"HAR subject-disjoint subject-weighted effects. Positive size reduction favors removal; positive coverage difference means higher selected-subset coverage. Effect cells show estimate and the exactly reproduced 95\% percentile interval from the frozen two-way seed/subject bootstrap. Each contrast has 100 seed $\times$ subject cells from 20 seeds and 26 unique held-out subject identifiers; these cells and the 146,500 grid rows are not independent subjects.",
        "tab:t5-har-compact",
        ["Model/path", "Cells", "Cluster structure", "Size reduction", "Coverage difference", "Bootstrap reps"],
        body,
    )


def compact_t5b() -> None:
    src = rows(FULL / "table_t5b_numerical_diagnostics.csv")
    if len(src) != 9:
        raise AssertionError(f"T5b row count: {len(src)}")
    body = []
    for r in src:
        body.append([
            r["dataset"], {"base": "Base", "ts": "TS", "confts": "ConfTS"}[r["scaling"]],
            f'{int(r["rows"]):,}', f'{int(r["raw_boundary_flagged_rows"]):,}',
            f'{int(r["scaling_induced_flagged_rows"]):,}', f'{num(r["mean_coverage"]):.6f}',
            f'{num(r["mean_empty_set_rate"]):.6f}',
        ])
    write_tex(
        OUT / "table_t5b_numerical_diagnostics_main.tex",
        "Numerical-boundary diagnostics over the full frozen dependent grid. Raw and scaling-induced flag counts are grid-row frequencies and must not be interpreted as independent model-, seed-, subject-, or window-level failure probabilities. Pooled mean coverage spans multiple operating points and is not a single nominal-coverage estimate. No flagged rows were excluded.",
        "tab:t5b-numerical",
        ["Dataset", "Scaling", "Rows", "Raw flags", "Induced flags", "Mean coverage", "Mean empty-set rate"],
        body,
        table_star=False,
        size_command=r"\small",
    )


if __name__ == "__main__":
    compact_t1()
    compact_t2()
    compact_h1()
    compact_baselines()
    compact_t4()
    compact_t5()
    compact_t5b()
    expected = {
        "table_t2_primary_compact.csv": 12,
        "table_t3_h1_compact.csv": 12,
        "table_t3_matched_baselines_compact.csv": 12,
        "table_t4_scaling_compact.csv": 12,
        "table_t5_har_subject_compact.csv": 4,
    }
    for name, count in expected.items():
        actual = len(rows(OUT / name))
        if actual != count:
            raise AssertionError(f"{name}: {actual} != {count}")
    print("PASS: compact manuscript tables built from frozen reporting sources")
